<html>

    <head>
		<title>ZF2 Basics</title>
		<style>
		body {
			font-family: Arial;
		}
		
		#nav {
			text-align: center;
			width: 100%;
		}
		</style>
    </head>

    <body>
		<div id="nav">
			<a href="/">Application Module - Index Controller - index action</a><br />
			<a href="/index/test">Application Module - Index Controller - test action</a><br />
			<a href="/test">Application Module - Test Controller - index action</a><br /> 
			<a href="/test1">Test1 Module - Index Controller - index action</a><br />
			<a href="/test1/foo/index">Test1 Module - Foo Controller - index action</a><br />
			<hr />
			<br />
		</div>
		<?php
		echo $this->content;
		?>
    </body>

</html>
